server:
    servlet:
        encoding:
            charset: UTF-8
    port: ${SERVER_PORT:8080}
    compression:
        enabled: true

spring:
    application:
        name: PriziQ!
    main:
        lazy-initialization: true
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false

    datasource:
        driverClassName: org.postgresql.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    data:
        web:
            pageable:
                one-indexed-parameters: true

    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 25MB

    mail:
        host: ${MAIL_HOST:smtp.gmail.com}
        port: ${MAIL_PORT:587}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

priziq:
    frontend:
        base-url: ${FRONTEND_BASE_URL:http://localhost:5173}
    account:
        base-password: ${ACCOUNT_BASE_PASSWORD:base_pass}
    allowed-init: ${ALLOWED_INIT:true}

jwt:
    access-signer-key: ${JWT_ACCESS_SIGNER_KEY}
    refresh-signer-key: ${JWT_REFRESH_SIGNER_KEY}
    access-token-duration-in-seconds: ${JWT_ACCESS_TOKEN_DURATION:3600} # 1h
    refresh-token-duration-in-seconds: ${JWT_REFRESH_TOKEN_DURATION:604800} # 7 days

aws:
    credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
    s3:
        bucketName: ${AWS_BUCKET_NAME}
        region: ${AWS_REGION}

file:
    allowedTypes: ${FILE_ALLOWED_TYPES:image/jpeg,image/png,image/jpg}
    maxSize: ${FILE_MAX_SIZE:5242880} # 5 MB
    minSize: ${FILE_MIN_SIZE:1024} # 1 KB

session:
    code:
        characters: ${SESSION_CODE_CHARACTERS:ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789}
        length: ${SESSION_CODE_LENGTH:6}
        max-attempts: ${SESSION_CODE_MAX_ATTEMPTS:10}