server:
    servlet:
        encoding:
            charset: UTF-8
    port: ${SERVER_PORT:8080}
    compression:
        enabled: true

spring:
    application:
        name: PriziQ!
    main:
        lazy-initialization: true
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false

    datasource:
        driverClassName: org.postgresql.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    data:
        web:
            pageable:
                one-indexed-parameters: true

    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 25MB

    mail:
        host: ${MAIL_HOST:smtp.gmail.com}
        port: ${MAIL_PORT:587}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

priziq:
    frontend:
        base-url: ${FRONTEND_BASE_URL:http://localhost:5173}
    account:
        base-password: ${ACCOUNT_BASE_PASSWORD:base_pass}
    allowed-init: ${ALLOWED_INIT:true}
    submission:
        base-score: ${SUBMISSION_BASE_SCORE:30}
        time-decrement: ${SUBMISSION_TIME_DECREMENT:1}
    quiz:
        default:
            question: ${QUIZ_DEFAULT_QUESTION:Default question}
            time_limit_seconds: ${QUIZ_DEFAULT_TIME_LIMIT_SECONDS:30}
            point_type: ${QUIZ_DEFAULT_POINT_TYPE:STANDARD}
        reorder:
            step1: ${QUIZ_REORDER_STEP1:Step 1}
            step2: ${QUIZ_REORDER_STEP2:Step 2}
            default_step: ${QUIZ_REORDER_DEFAULT_STEP:Default step}
        choice:
            option1: ${QUIZ_CHOICE_OPTION1:Option 1}
            option2: ${QUIZ_CHOICE_OPTION2:Option 2}
            option3: ${QUIZ_CHOICE_OPTION3:Option 3}
            option4: ${QUIZ_CHOICE_OPTION4:Option 4}
            wrong_answer: ${QUIZ_CHOICE_WRONG_ANSWER:Wrong answer}
        type_answer:
            default: ${QUIZ_TYPE_ANSWER_DEFAULT:Default answer}
        true_false:
            option_true: ${QUIZ_CHOICE_TRUE:True}
            option_false: ${QUIZ_CHOICE_FALSE:False}
        default_activity:
            title: ${QUIZ_DEFAULT_ACTIVITY_TITLE:Default Quiz}
            description: ${QUIZ_DEFAULT_ACTIVITY_DESCRIPTION:A default multiple-choice quiz}
            is_published: ${QUIZ_DEFAULT_ACTIVITY_IS_PUBLISHED:true}
    slide:
        default:
            transition_duration: ${SLIDE_DEFAULT_TRANSITION_DURATION:1}
            auto_advance_seconds: ${SLIDE_DEFAULT_AUTO_ADVANCE_SECONDS:0}

jwt:
    access-signer-key: ${JWT_ACCESS_SIGNER_KEY}
    refresh-signer-key: ${JWT_REFRESH_SIGNER_KEY}
    access-token-duration-in-seconds: ${JWT_ACCESS_TOKEN_DURATION:3600} # 1h
    refresh-token-duration-in-seconds: ${JWT_REFRESH_TOKEN_DURATION:604800} # 7 days

aws:
    credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
    s3:
        bucketName: ${AWS_BUCKET_NAME}
        region: ${AWS_REGION}

file:
    allowedTypes: ${FILE_ALLOWED_TYPES:image/jpeg,image/png,image/jpg}
    maxSize: ${FILE_MAX_SIZE:5242880} # 5 MB
    minSize: ${FILE_MIN_SIZE:1024} # 1 KB

session:
    code:
        characters: ${SESSION_CODE_CHARACTERS:ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789}
        length: ${SESSION_CODE_LENGTH:6}
        max-attempts: ${SESSION_CODE_MAX_ATTEMPTS:10}